<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="testriq" failures="0" tests="4" name="testcases.TC_02_Add_To_Cart" time="12.370" errors="1" timestamp="2025-01-22T15:47:50 IST" skipped="3">
  <testcase classname="testcases.TC_02_Add_To_Cart" name="configuration" time="12.370">
    <error message="JSONObject[&quot;email&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["email"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at org.json.JSONObject.getString(JSONObject.java:857)
at testcases.TC_02_Add_To_Cart.loadLoginCredentials(TC_02_Add_To_Cart.java:83)
at testcases.TC_02_Add_To_Cart.configuration(TC_02_Add_To_Cart.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- configuration -->
  <testcase classname="testcases.TC_02_Add_To_Cart" name="WithLoginAddToCartAndCheckout" time="0.000">
    <skipped/>
  </testcase> <!-- WithLoginAddToCartAndCheckout -->
  <testcase classname="testcases.TC_02_Add_To_Cart" name="WithoutLoginAddToCart" time="0.000">
    <skipped/>
  </testcase> <!-- WithoutLoginAddToCart -->
  <testcase classname="testcases.TC_02_Add_To_Cart" name="RemoveProductFromCart" time="0.000">
    <skipped/>
  </testcase> <!-- RemoveProductFromCart -->
</testsuite> <!-- testcases.TC_02_Add_To_Cart -->
